# Generated by Django 4.1.5 on 2023-02-07 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.CharField(max_length=120, verbose_name='описание')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(verbose_name='Дата окончания')),
                ('image', models.ImageField(upload_to='todo/images/', verbose_name='картинка')),
                ('is_done', models.BooleanField(default=False, verbose_name='сделано?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todoes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
